### ISSUE TITLE
Beanmapper wrongfully assumes a HibernateProxy is there when you use an inner class

### ISSUE THREAD

**Issue by SanderBenschop** [42BV/beanmapper#138]
I was using an inner class in a Form because the outer form just consisted of a lists of form objects, and I ran into an ArrayIndexOutOfBoundsException:

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at io.beanmapper.spring.unproxy.HibernateAwareBeanUnproxy.unproxy(HibernateAwareBeanUnproxy.java:16)
	at io.beanmapper.core.unproxy.SkippingBeanUnproxy.unproxy(SkippingBeanUnproxy.java:40)
	at io.beanmapper.strategy.MapToClassStrategy.map(MapToClassStrategy.java:20)
	at io.beanmapper.BeanMapper.map(BeanMapper.java:29)
	at io.beanmapper.core.collections.AbstractCollectionHandler.mapItem(AbstractCollectionHandler.java:42)
	at io.beanmapper.core.collections.ListCollectionHandler.copy(ListCollectionHandler.java:13)
	at io.beanmapper.core.collections.ListCollectionHandler.copy(ListCollectionHandler.java:8)
	at io.beanmapper.strategy.MapCollectionStrategy.map(MapCollectionStrategy.java:32)
	at io.beanmapper.BeanMapper.map(BeanMapper.java:29)
	at io.beanmapper.core.converter.collections.CollectionConverter.convert(CollectionConverter.java:38)
	at io.beanmapper.strategy.AbstractMapStrategy.convert(AbstractMapStrategy.java:137)
	at io.beanmapper.strategy.AbstractMapStrategy.copySourceToTarget(AbstractMapStrategy.java:83)
	at io.beanmapper.strategy.AbstractMapStrategy.processProperty(AbstractMapStrategy.java:201)
	at io.beanmapper.strategy.AbstractMapStrategy.processProperties(AbstractMapStrategy.java:162)
	at io.beanmapper.strategy.MapToInstanceStrategy.map(MapToInstanceStrategy.java:24)
	at io.beanmapper.strategy.MapToClassStrategy.map(MapToClassStrategy.java:33)
	at io.beanmapper.BeanMapper.map(BeanMapper.java:29)
	at io.beanmapper.BeanMapper.map(BeanMapper.java:59)
```

With something similar to this as a form:

```java
public class SpoonDrawerForm {

    @BeanCollection(elementType = Spoon.class)
    public List<SpoonForm> spoons;

    public static class SpoonForm {
        public Long id;
        public Boolean polished;
    }
}
```

This happened in the following class:

```java
public class HibernateAwareBeanUnproxy implements BeanUnproxy {

    /**
     * {@inheritDoc}
     */
    @Override
    public Class<?> unproxy(Class<?> beanClass) {
        String name = beanClass.getName();
        if (name.contains("$")) {
            Class<?> interfaceClass = beanClass.getInterfaces()[0];
            if (interfaceClass.equals(HibernateProxy.class)) {
                return beanClass.getSuperclass();
            } else {
                return beanClass.getInterfaces()[0];
            }
        }
        return beanClass;
    }

}
```

This check assumes that a class that contains $ in the name is a Hibernate proxy class, but an inner class contains this dollar sign also.

**Comment by marcus-talbot42** [comment]
Fixed by 42BV/beanmapper-spring#47
