### ISSUE TITLE
Concurrency: getConverterOptional

### ISSUE THREAD

**Issue by jeroenvs** [42BV/beanmapper#26]
Whenever I invoke the bean mapper async with multiple requests errors occur:

java.lang.NullPointerException
	at io.beanmapper.BeanMapper.getConverterOptional(BeanMapper.java:296)

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at io.beanmapper.BeanMapper.getConverterOptional(BeanMapper.java:295)
	at io.beanmapper.BeanMapper.isConverterFor(BeanMapper.java:304)

Which relates to the following lines:

        for (BeanConverter converter : beanConverters) {
            if (converter.match(sourceClass, targetClass)) {

-----

You could wrap the beanConverters in a new collection before iterating over them and add a null-safety check on the match line.

**Comment by Rickvanderwaal** [comment]
#26 added in release v0.2.15.
