### ISSUE TITLE
NullPointerException in MapToDynamicClassStrategy

### ISSUE THREAD

**Issue by Rickvanderwaal** [42BV/beanmapper#49]
The ClassPool in MapToDynamicClassStrategy.java throws a NullPointerException because the classes of your project does not exist in the ClassPool.

**Comment by robert-bor** [comment]
```
java.lang.NullPointerException
	at io.beanmapper.exceptions.BeanDynamicClassGenerationException.<init>(BeanDynamicClassGenerationException.java:8)
	at io.beanmapper.strategy.MapToDynamicClassStrategy.getOrCreateGeneratedClass(MapToDynamicClassStrategy.java:89)
	at io.beanmapper.strategy.MapToDynamicClassStrategy.map(MapToDynamicClassStrategy.java:53)
	at io.beanmapper.BeanMapper.map(BeanMapper.java:34)
	at io.beanmapper.BeanMapper.map(BeanMapper.java:150)
	at io.beanmapper.controller.AddressController.partialUpdate(AddressController.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by robert-bor** [comment]
![screen shot 2016-03-08 at 15 48 54](https://cloud.githubusercontent.com/assets/813749/13604884/444a4510-e545-11e5-8667-436409dd97b9.png)

**Comment by robert-bor** [comment]
Javassist is unable to find the model class, because it did not register its classloader. 

Concept solution:

```java
    public MapToDynamicClassStrategy(BeanMapper beanMapper, Configuration configuration) {
        super(beanMapper, configuration);
        this.classPool = ClassPool.getDefault();
        this.classPool.insertClassPath(new ClassClassPath(configuration.determineTargetClass()));
    }
```

determineTargetClass will return the class of the target, whether mapping takes places to an instance (ie, target) or to a class (ie, targetClass).

**Comment by Rickvanderwaal** [comment]
Thanks for help @robert-bor !
