### ISSUE TITLE
exception in beanmapper class DefaultBeanUnproxy: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ailbertriksen** [42BV/beanmapper#53]
Stacktrace:
```
apr 05, 2016 7:45:36 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [dispatcher] in context with path [/api] threw exception [Request processing failed; nested exception is java.lang.ArrayIndexOutOfBoundsException: 0] with root cause
java.lang.ArrayIndexOutOfBoundsException: 0
	at io.beanmapper.core.unproxy.DefaultBeanUnproxy.unproxy(DefaultBeanUnproxy.java:21)
	at io.beanmapper.core.unproxy.SkippingBeanUnproxy.unproxy(SkippingBeanUnproxy.java:36)
	at io.beanmapper.BeanMapper.getBeanMatch(BeanMapper.java:176)
	at io.beanmapper.BeanMapper.matchSourceToTarget(BeanMapper.java:166)
	at io.beanmapper.BeanMapper.map(BeanMapper.java:149)
	at io.beanmapper.BeanMapper.map(BeanMapper.java:114)
	at io.beanmapper.BeanMapper.map(BeanMapper.java:90)
	at nl.mad.voliere.buizerd.model.website.WebsiteService.checkNow(WebsiteService.java:269)
	at nl.mad.voliere.buizerd.model.website.WebsiteService$$FastClassBySpringCGLIB$$11439aa7.invoke(<generated>)
```

code of DefaultBeanUnproxy:
```
public class DefaultBeanUnproxy implements BeanUnproxy {
    public DefaultBeanUnproxy() {
    }
    public Class<?> unproxy(Class<?> beanClass) {
        String name = beanClass.getName();
==>     return name.contains("$")?beanClass.getInterfaces()[0]:beanClass;
    }
}
```
name is: nl.mad.voliere.buizerd.checker.WebsiteCheckerExecutor$UrlTestResult
UrlTestResult is an inner class of WebsiteCheckerExecutor. There are no interfaces.

**Comment by Rickvanderwaal** [comment]
This issue is fixed in the next release of BeanMapper.
For now you can use BeanMapper.addProxySkipClass(UrlTestResult.class)

**Comment by ailbertriksen** [comment]
I still got the exception. This is my code:
```
    @Inject
    private BeanMapper beanMapper;

....
        beanMapper.addProxySkipClass(WebsiteCheckerExecutor.UrlTestResult.class);
        UrlTestResultForm urlTestResultForm = beanMapper.map(urlTestResult, UrlTestResultForm.class);
```

**Comment by Rickvanderwaal** [comment]
workaround is not working, this issue including the workaround will be fixed in the next release of BeanMapper.
