### ISSUE TITLE
Exception when mapping from Arrays.asList

### ISSUE THREAD

**Issue by arjanvlek** [42BV/beanmapper#68]
BeanMapper (v0.3.1) throws an exception when mapping an object that was created from a regular array using Arrays.asList.

Example: Mapping

    Collection<MyAwesomeEnum> collection = Arrays.asList(MyAwesomeEnum.values()) ;
    Collection<MyAwesomeResult> result =  beanMapper.map(collection, MyAwesomeResult.class);

Throws

    io.beanmapper.exceptions.BeanConstructException: No suitable constructor found while trying to bean construct class java.util.Arrays$ArrayList
	at io.beanmapper.core.constructor.DefaultBeanInitializer.instantiate(DefaultBeanInitializer.java:24)
	at io.beanmapper.strategy.MapCollectionStrategy.map(MapCollectionStrategy.java:20)
	at io.beanmapper.BeanMapper.map(BeanMapper.java:33)
	at io.beanmapper.BeanMapper.map(BeanMapper.java:112))`

A workaround is to construct a new arraylist on the collection created using Arrays.asList.
Example:

    Collection<MyAwesomeEnum> collection = new ArrayList<>(Arrays.asList(MyAwesomeEnum.values());

**Comment by robert-bor** [comment]
Problem also occurs with anonymous classes when passed at the map level. It does not occur when the mapped instance is nested somewhere within the source.
